"""
新增Schema演进相关表

- question_attributes: 扩展属性表，支持版本控制
- book_libraries: 书籍库版本表
- question_book_refs: 题目与书籍关联表
"""

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '002_add_schema_evolution_tables'
down_revision = '001_create_upload_records'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 改造 questions 表，添加扩展字段
    op.add_column('questions', sa.Column('options', sa.Text(), nullable=True, comment='选项（JSON字符串）'))
    op.add_column('questions', sa.Column('stem_images', sa.Text(), nullable=True, comment='题干图片（JSON字符串）'))
    op.add_column('questions', sa.Column('status', sa.String(20), nullable=False, server_default='draft', comment='状态：draft/active/confirmed'))
    op.add_column('questions', sa.Column('deleted_at', sa.DateTime(), nullable=True, comment='删除时间（软删除）'))
    op.add_column('questions', sa.Column('is_deleted', sa.Boolean(), nullable=False, server_default='0', comment='是否已删除'))
    
    # 创建软删除索引
    op.create_index('idx_questions_is_deleted', 'questions', ['is_deleted'])
    op.create_index('idx_questions_status', 'questions', ['status'])
    
    # 2. 创建扩展属性表
    op.create_table(
        'question_attributes',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('question_id', sa.String(100), nullable=False, comment='题目ID'),
        sa.Column('schema_version', sa.String(10), nullable=False, comment='Schema版本'),
        sa.Column('schema_name', sa.String(50), nullable=False, comment='Schema名称'),
        sa.Column('attribute_data', sa.Text(), nullable=False, comment='属性数据（JSON字符串）'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1', comment='是否生效'),
        sa.Column('valid_from', sa.DateTime(), nullable=True, comment='生效时间'),
        sa.Column('valid_until', sa.DateTime(), nullable=True, comment='失效时间'),
        sa.Column('migration_notes', sa.Text(), nullable=True, comment='迁移说明'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        sa.Column('created_by', sa.String(100), nullable=True, comment='创建者'),
        
        # 主键约束
        sa.PrimaryKeyConstraint('id'),
        
        # 唯一约束
        sa.UniqueConstraint('question_id', 'schema_version', name='uq_question_attribute_version'),
        
        # 外键约束
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
        
        # 注释
        comment='题目扩展属性表，支持Schema版本控制'
    )
    
    # 创建索引
    op.create_index('idx_qa_question_id', 'question_attributes', ['question_id'])
    op.create_index('idx_qa_schema_version', 'question_attributes', ['schema_version'])
    op.create_index('idx_qa_is_active', 'question_attributes', ['is_active'])
    op.create_index('idx_qa_created_at', 'question_attributes', ['created_at'])
    
    # 3. 创建书籍库表
    op.create_table(
        'book_libraries',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('library_version', sa.String(20), nullable=False, comment='书籍库版本'),
        sa.Column('library_name', sa.String(100), nullable=False, comment='书籍库名称'),
        sa.Column('publisher', sa.String(100), nullable=True, comment='出版社'),
        sa.Column('effective_date', sa.Date(), nullable=True, comment='生效日期'),
        sa.Column('is_active', sa.Boolean(), nullable=False, server_default='1', comment='是否生效'),
        sa.Column('schema_definition', sa.Text(), nullable=True, comment='Schema定义（JSON）'),
        sa.Column('migration_script', sa.Text(), nullable=True, comment='迁移脚本'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        
        # 主键约束
        sa.PrimaryKeyConstraint('id'),
        
        # 唯一约束
        sa.UniqueConstraint('library_version', name='uq_book_library_version'),
        
        # 注释
        comment='书籍库版本表'
    )
    
    # 创建索引
    op.create_index('idx_bl_library_version', 'book_libraries', ['library_version'])
    op.create_index('idx_bl_is_active', 'book_libraries', ['is_active'])
    
    # 4. 创建题目与书籍关联表
    op.create_table(
        'question_book_refs',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('question_id', sa.String(100), nullable=False, comment='题目ID'),
        sa.Column('book_library_version', sa.String(20), nullable=False, comment='书籍库版本'),
        sa.Column('book_name', sa.String(100), nullable=True, comment='书籍名称'),
        sa.Column('grade', sa.Integer(), nullable=True, comment='年级'),
        sa.Column('semester', sa.String(10), nullable=True, comment='学期（上/下）'),
        sa.Column('unit', sa.String(50), nullable=True, comment='单元'),
        sa.Column('page', sa.Integer(), nullable=True, comment='页码'),
        sa.Column('question_number', sa.Integer(), nullable=True, comment='题号'),
        sa.Column('metadata', sa.Text(), nullable=True, comment='元数据（JSON）'),
        sa.Column('created_at', sa.DateTime(), nullable=False, server_default=sa.text('CURRENT_TIMESTAMP')),
        
        # 主键约束
        sa.PrimaryKeyConstraint('id'),
        
        # 唯一约束
        sa.UniqueConstraint('question_id', 'book_library_version', name='uq_question_book_ref'),
        
        # 外键约束
        sa.ForeignKeyConstraint(['question_id'], ['questions.id'], ondelete='CASCADE'),
        sa.ForeignKeyConstraint(['book_library_version'], ['book_libraries.library_version'], ondelete='CASCADE'),
        
        # 注释
        comment='题目与书籍关联表'
    )
    
    # 创建索引
    op.create_index('idx_qbr_question_id', 'question_book_refs', ['question_id'])
    op.create_index('idx_qbr_book_version', 'question_book_refs', ['book_library_version'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 1. 删除题目与书籍关联表
    op.drop_index('idx_qbr_book_version', table_name='question_book_refs')
    op.drop_index('idx_qbr_question_id', table_name='question_book_refs')
    op.drop_table('question_book_refs')
    
    # 2. 删除书籍库表
    op.drop_index('idx_bl_is_active', table_name='book_libraries')
    op.drop_index('idx_bl_library_version', table_name='book_libraries')
    op.drop_table('book_libraries')
    
    # 3. 删除扩展属性表
    op.drop_index('idx_qa_created_at', table_name='question_attributes')
    op.drop_index('idx_qa_is_active', table_name='question_attributes')
    op.drop_index('idx_qa_schema_version', table_name='question_attributes')
    op.drop_index('idx_qa_question_id', table_name='question_attributes')
    op.drop_table('question_attributes')
    
    # 4. 恢复 questions 表
    op.drop_index('idx_questions_status', table_name='questions')
    op.drop_index('idx_questions_is_deleted', table_name='questions')
    op.drop_column('questions', 'is_deleted')
    op.drop_column('questions', 'deleted_at')
    op.drop_column('questions', 'status')
    op.drop_column('questions', 'stem_images')
    op.drop_column('questions', 'options')
    
    # ### end Alembic commands ###
