"""
创建监控日志表

用于存储后端运行时的错误日志、性能指标和系统事件
"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '003_create_monitor_logs_table'
down_revision = '002_add_schema_evolution_tables'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 创建监控日志表
    op.create_table(
        'monitor_logs',
        sa.Column('id', sa.String(36), primary_key=True, comment='日志ID (UUID)'),
        
        # 日志类型
        sa.Column('log_type', sa.String(20), nullable=False, comment='日志类型: error/performance/event'),
        
        # 请求信息
        sa.Column('request_id', sa.String(36), nullable=True, comment='请求唯一标识'),
        sa.Column('method', sa.String(10), nullable=True, comment='HTTP方法'),
        sa.Column('path', sa.String(500), nullable=True, comment='请求路径'),
        sa.Column('status_code', sa.Integer(), nullable=True, comment='HTTP状态码'),
        
        # 性能数据
        sa.Column('response_time_ms', sa.Integer(), nullable=True, comment='响应时间(毫秒)'),
        
        # 错误信息
        sa.Column('error_message', sa.Text(), nullable=True, comment='错误消息'),
        sa.Column('error_stack', sa.Text(), nullable=True, comment='堆栈信息'),
        sa.Column('request_params', sa.Text(), nullable=True, comment='请求参数(JSON)'),
        
        # 元数据
        sa.Column('user_id', sa.String(100), nullable=True, comment='操作用户ID'),
        sa.Column('ip_address', sa.String(50), nullable=True, comment='客户端IP'),
        
        # 时间
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), comment='创建时间'),
        
        # 注释
        comment='监控日志表，用于存储错误日志、性能指标和系统事件'
    )
    
    # 创建索引
    op.create_index('idx_monitor_logs_type', 'monitor_logs', ['log_type'])
    op.create_index('idx_monitor_logs_created_at', 'monitor_logs', ['created_at'])
    op.create_index('idx_monitor_logs_path', 'monitor_logs', ['path'])
    op.create_index('idx_monitor_logs_status_code', 'monitor_logs', ['status_code'])
    
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    
    # 删除索引
    op.drop_index('idx_monitor_logs_status_code', table_name='monitor_logs')
    op.drop_index('idx_monitor_logs_path', table_name='monitor_logs')
    op.drop_index('idx_monitor_logs_created_at', table_name='monitor_logs')
    op.drop_index('idx_monitor_logs_type', table_name='monitor_logs')
    
    # 删除表
    op.drop_table('monitor_logs')
    
    # ### end Alembic commands ###